// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE2tQqEuFLJy1DUmY9otLkIG2xKU7whpM',
    appId: '1:861678833557:android:74686a47dbdbcefa7db09c',
    messagingSenderId: '861678833557',
    projectId: 'my-auth-e91c2',
    storageBucket: 'my-auth-e91c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmAebxp44PbTwFAWIR_3Q8Q97RTdnJSig',
    appId: '1:861678833557:ios:1f37d1b318b1709e7db09c',
    messagingSenderId: '861678833557',
    projectId: 'my-auth-e91c2',
    storageBucket: 'my-auth-e91c2.appspot.com',
    androidClientId: '861678833557-apsvuf666mt4d9psr499hvn440rs170h.apps.googleusercontent.com',
    iosClientId: '861678833557-6ld1o0bt0anmgpouj2kn0bek30vv0jht.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleMaps',
  );
}
